name: Add Labels to PR

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  label-bug:
    runs-on: ubuntu-latest
    steps:
      - name: Check for 'bug' in PR title
        if: contains(github.event.pull_request.title, 'bug')
        uses: octokit/request-action@v2.x
        id: bug-label
        with:
          route: POST /repos/:owner/:repo/issues/:issue_number/labels
          owner: ${{ github.event.repository.owner.login }}
          repo: ${{ github.event.repository.name }}
          issue_number: ${{ github.event.pull_request.number }}
          labels: bug
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

  label-enhancement:
    runs-on: ubuntu-latest
    steps:
      - name: Check for 'feature' in PR title
        if: contains(github.event.pull_request.title, 'feat')
        uses: octokit/request-action@v2.x
        id: enhancement-label
        with:
          route: POST /repos/:owner/:repo/issues/:issue_number/labels
          owner: ${{ github.event.repository.owner.login }}
          repo: ${{ github.event.repository.name }}
          issue_number: ${{ github.event.pull_request.number }}
          labels: enhancement
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

  label-invalid:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR is closed and not merged
        if: github.event.pull_request.merged == false && github.event.pull_request.state == 'closed'
        uses: octokit/request-action@v2.x
        id: invalid-label
        with:
          route: POST /repos/:owner/:repo/issues/:issue_number/labels
          owner: ${{ github.event.repository.owner.login }}
          repo: ${{ github.event.repository.name }}
          issue_number: ${{ github.event.pull_request.number }}
          labels: invalid
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

  remove-milestone:
    runs-on: ubuntu-latest
    steps:
      - name: Remove Milestone for closed, unmerged PR
        if: github.event.pull_request.merged == false && github.event.pull_request.state == 'closed'
        uses: octokit/request-action@v2.x
        id: milestone
        with:
          route: DELETE /repos/:owner/:repo/issues/:issue_number/milestone
          owner: ${{ github.event.repository.owner.login }}
          repo: ${{ github.event.repository.name }}
          issue_number: ${{ github.event.pull_request.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
