name: Add Labels to PR

on:
  pull_request:
    types: [opened, edited]

jobs:
  label-enhancement:
    if: contains(github.event.pull_request.title, 'feat')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['enhancement']
            })

  label-bug:
    if: contains(github.event.pull_request.title, 'bug')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['bug']
            })

  label-twolabels:
    if: contains(github.event.pull_request.title, 'bang')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            await github.rest.issues.removeAllLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
            await github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['wontfix', 'invalid', 'question']
            })

 remove-milestone:
    if: contains(github.event.pull_request.title, 'Roar')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            await github.rest.issues.removeMilestone({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo
            });
