name: Add Labels to PR

on:
  pull_request:
    types: [opened, edited, closed]

jobs:
  label-enhancement:
    if: contains(github.event.pull_request.title, 'feat')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['enhancement']
            });

  label-bug:
    if: contains(github.event.pull_request.title, 'bug') || contains(github.event.pull_request.title, 'fix') 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['bug']
            });

  label-invalid:
    if: contains(github.event.pull_request.title, 'invalid') || (github.event.pull_request.merged == false && github.event.pull_request.state == 'closed')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            await github.rest.issues.update({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              milestone: null
            });
            await github.rest.issues.removeAllLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            await github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['invalid']
            });
